### ISSUE TITLE
Repetier-host crashes when Bed height map number of points is 1.

### ISSUE THREAD

**Issue by VladimirP1** [repetier/Repetier-Host#333]
When nx or ny are 1, division by 0 happens.
https://github.com/repetier/Repetier-Host/blob/f5d808611a57c7aeb4f3aa6a5c70446f11f63c54/src/RepetierHost/view/calibration/BedHeightMap.cs#L74

**Comment by repetier** [comment]
Thanks. I have replaced the inputs to validated floats and integers with min=2, so in the next release it should be no problem. Thanks.
