### ISSUE TITLE
G-Code Binary (Won't load into Repetier Host)

### ISSUE THREAD

**Issue by Harsanjit** [repetier/Repetier-Host#334]
Recently, I have tried printing a couple different objects using my Felix 3.0 printer (Using the Repetier-Host firmware). I saved and converted the G-Code using the Repetier-Host software on my computer and uploaded it to a micro-SD card that I inserted into my printer so it could print from the card. Half way through the print, I got a decoupling issue and now have to restart the print. I am trying to print from the current layer and thought I could simply load the G-Code that I originally uploaded to the SD-Card onto the Repetier-Host software for desktop but since the G-Code was converted into binary, I am unable to view or change the G-Code that I load. Since I made some scaling changes to the original model, I no longer know exactly how I can convert the binary G-Code back into the original one.

**Comment by repetier** [comment]
While it is technically possible, there is no way to read it back. Binary is meant as fast and short alternative for printing files, not for working on them.
