### ISSUE TITLE
Download link doesn't work

### ISSUE THREAD

**Issue by mociepka** [repetier/Repetier-Host#340]
[Download link for linux](http://download.repetier.com/files/host/linux/repetierHostLinux_1_5_6.tgz) archive doesn't work:

![image](https://cloud.githubusercontent.com/assets/1870738/10290135/a55a0d9e-6ba2-11e5-83b7-5151ca38598d.png)

What do you think about creating releases on github and attaching archives to them? That will solve hosting problems.

![image](https://cloud.githubusercontent.com/assets/1870738/10290216/11a83656-6ba3-11e5-9d67-6488bf1e2cfa.png)

**Comment by repetier** [comment]
We had a server downtime and download manager did not start. Is now fixed. Thanks.

Github is not a solution for us. We do not use it any more for the host.
