### ISSUE TITLE
repetier host on osx with mono and linux version

### ISSUE THREAD

**Issue by celevra** [repetier/Repetier-Host#341]
Hi,

repetier host for osx is very outdated. isn't it possible to run the linux Version on a mac with mono installed? 
slic3r is available native for osx.

regards

celevra

**Comment by Flole998** [comment]
I already tried that and for some reason it doesn't work. It is launching but then I keep getting an exception in one of the timer functions. Would be great if this could be fixed though.

**Comment by repetier** [comment]
Even if it runs it is a hell. Forms library for mac which is used for the gui is still too buggy to use it.
