### ISSUE TITLE
Crash when changing Antialias Method in Preferences (Mac / RH 1.00)

### ISSUE THREAD

**Issue by mriveralee** [repetier/Repetier-Host#352]
Steps to Repro:
1) Click "Repetier Host-Mac" in menu bar

2) Go to Preferences -> 3D Visualization -> Antialiasing Method
<img width="1280" alt="screen shot 2016-08-03 at 12 43 56 pm" src="https://cloud.githubusercontent.com/assets/1381319/17373894/3c639142-5978-11e6-8b46-1ef468ca9de0.png">

3) Change the Antialiasing Method --> Crash

<img width="435" alt="screen shot 2016-08-03 at 12 44 03 pm" src="https://cloud.githubusercontent.com/assets/1381319/17373895/3d93285c-5978-11e6-8808-3c1d0d56f951.png">

Device Info:
OS: Mac (OS 10.11.16 - El Capitan)
Repetier Host Version: 1.00

Call Stack:
<img width="1162" alt="screen shot 2016-08-03 at 12 44 32 pm" src="https://cloud.githubusercontent.com/assets/1381319/17373900/40dcfe66-5978-11e6-8438-7f22bc14765e.png">

**Comment by repetier** [comment]
Found the problem and solved it for 1.0.1 coming soon.
