### ISSUE TITLE
Slow Zooming  and Frame rate drop when Using Trackpad to Scroll (Mac / RH 1.00)

### ISSUE THREAD

**Issue by mriveralee** [repetier/Repetier-Host#353]
Use two-finger touch on trackpad to scroll in the visualization. Framerate drops from ~1900 FPS to 60 FPS and zoom is barely registered.

**Comment by repetier** [comment]
Thanks. Found the reason for dropping framerate, also this was not the problem for slow speed. That was just a bed selected speed factor. Fixed and much faster in 1.0.1 coming soon.
