### ISSUE TITLE
m117 parsing and triggers.

### ISSUE THREAD

**Issue by tecan** [repetier/Repetier-Host#386]
m117 parsing feedback strings during print to launch scripts. for custom actions like saving z height to a file, playing music during print or controlling other stepper drivers.

**Comment by repetier** [comment]
M117 would be a hack as it is for changing the printer lcd status screen. Hosts already react on many infos returned by firmware, but i guess you want to send host commands to the host. That is not required. If you want a host action just insert
@command
In the gcode and hist will execute the comand. See docs for available commands. Repetier-Server has here some more possibilities and also supports executing external commands  or running scripts from firmware response,

**Comment by tecan** [comment]
oh i see it needs a extcommands.xml file

**Comment by tecan** [comment]
i tried putting Repetier-Host/database/extcommands.xml in place with proper config. im unsure why it wont run.

**Comment by tecan** [comment]
oh all i have to do is @execute fullpathname to binary... i was trying it with gedit and it needs /usr/bin infront

**Comment by repetier** [comment]
Extcommands.xml is only required for server a this is more a security risk being a networkable host. After all you should only execute gcodes you generate or trust.
